const express = require('express');
const router = express.Router();
const execute = require('./connection');

// LOGIN
router.get("/maparuta", async(req,res)=>{
	
	const {token,codven,fecha} = req.query;

	let qr = `SELECT WEB_DOCUMENTOS.FECHA, WEB_DOCUMENTOS.CODDOC, WEB_DOCUMENTOS.CORRELATIVO, CLIENTES.NOMCLIENTE, CLIENTES.DIRCLIENTE, CLIENTES.EMAIL, WEB_DOCUMENTOS.TOTALCOSTO, 
                WEB_DOCUMENTOS.TOTALVENTA, VENDEDORES.NOMVEN, WEB_DOCUMENTOS.LAT, WEB_DOCUMENTOS.LONG
            FROM WEB_DOCUMENTOS LEFT OUTER JOIN
            VENDEDORES ON WEB_DOCUMENTOS.TOKEN = VENDEDORES.TOKEN AND WEB_DOCUMENTOS.CODVEN = VENDEDORES.CODVEN AND WEB_DOCUMENTOS.EMPNIT = VENDEDORES.EMPNIT LEFT OUTER JOIN
            CLIENTES ON WEB_DOCUMENTOS.TOKEN = CLIENTES.TOKEN AND WEB_DOCUMENTOS.CODCLIENTE = CLIENTES.CODCLIENTE AND WEB_DOCUMENTOS.EMPNIT = CLIENTES.EMPNIT
            WHERE (WEB_DOCUMENTOS.TOKEN = '${token}') AND (WEB_DOCUMENTOS.FECHA ='${fecha}') AND (WEB_DOCUMENTOS.CODVEN = '${codven}')`

        execute.Query(res,qr);

});
router.get("/vendedores", async(req,res)=>{
    
    const token = req.query.token;
    let qry = `SELECT CODVEN,NOMVEN FROM VENDEDORES WHERE TOKEN='${token}'`;
    execute.Query(res,qry);

}); 

router.get("/rptventas",async(req,res)=>{

	const {token,codven,fecha} = req.query;

	let qry = `SELECT WEB_DOCUMENTOS.CODVEN, VENDEDORES.NOMVEN, WEB_DOCUMENTOS.ANIO, WEB_DOCUMENTOS.MES, WEB_DOCUMENTOS.DIA, WEB_DOCUMENTOS.FECHA, WEB_DOCUMENTOS.CODDOC, 
				WEB_DOCUMENTOS.CORRELATIVO, CLIENTES.NOMCLIENTE, CLIENTES.DIRCLIENTE, WEB_DOCUMENTOS.TOTALVENTA, WEB_DOCUMENTOS.LAT, WEB_DOCUMENTOS.LONG
			FROM WEB_DOCUMENTOS LEFT OUTER JOIN
			CLIENTES ON WEB_DOCUMENTOS.CODCLIENTE = CLIENTES.CODCLIENTE AND WEB_DOCUMENTOS.EMPNIT = CLIENTES.EMPNIT AND WEB_DOCUMENTOS.TOKEN = CLIENTES.TOKEN LEFT OUTER JOIN
			VENDEDORES ON WEB_DOCUMENTOS.TOKEN = VENDEDORES.TOKEN AND WEB_DOCUMENTOS.CODVEN = VENDEDORES.CODVEN AND WEB_DOCUMENTOS.EMPNIT = VENDEDORES.EMPNIT
			WHERE (WEB_DOCUMENTOS.TOKEN = '${token}') AND (WEB_DOCUMENTOS.CODVEN = ${codven}) AND (WEB_DOCUMENTOS.FECHA = '${fecha}')`

	execute.Query(res,qry);

})

module.exports = router;