const express = require('express');
const router = express.Router();
const execute = require('./connection');

// OBTIENE EL TOTAL DE INVENTARIOS
router.get("/inventarios", async(req,res)=>{
  
  const token = req.query.token;
  
  let qr = `SELECT COMMUNITY_INVSALDO_SYNC.EMPNIT, COMMUNITY_EMPRESAS_SYNC.EMPNOMBRE, COMMUNITY_INVSALDO_SYNC.CODPROD, COMMUNITY_PRODUCTOS_SYNC.DESPROD, COMMUNITY_INVSALDO_SYNC.ENTRADAS, 
  COMMUNITY_INVSALDO_SYNC.SALIDAS, COMMUNITY_INVSALDO_SYNC.SALDO, COMMUNITY_MARCAS.DESMARCA, COMMUNITY_PRODUCTOS_SYNC.COSTO, (ISNULL((COMMUNITY_PRODUCTOS_SYNC.COSTO * COMMUNITY_INVSALDO_SYNC.SALDO),0)) AS TOTALCOSTO
  FROM COMMUNITY_MARCAS RIGHT OUTER JOIN
  COMMUNITY_PRODUCTOS_SYNC ON COMMUNITY_MARCAS.TOKEN = COMMUNITY_PRODUCTOS_SYNC.TOKEN AND COMMUNITY_MARCAS.CODMARCA = COMMUNITY_PRODUCTOS_SYNC.CODMARCA AND 
  COMMUNITY_MARCAS.EMPNIT = COMMUNITY_PRODUCTOS_SYNC.EMPNIT RIGHT OUTER JOIN
  COMMUNITY_INVSALDO_SYNC LEFT OUTER JOIN
  COMMUNITY_EMPRESAS_SYNC ON COMMUNITY_INVSALDO_SYNC.TOKEN = COMMUNITY_EMPRESAS_SYNC.TOKEN AND 
  COMMUNITY_INVSALDO_SYNC.EMPNIT = COMMUNITY_EMPRESAS_SYNC.EMPNIT ON COMMUNITY_PRODUCTOS_SYNC.TOKEN = COMMUNITY_INVSALDO_SYNC.TOKEN AND 
  COMMUNITY_PRODUCTOS_SYNC.CODPROD = COMMUNITY_INVSALDO_SYNC.CODPROD AND COMMUNITY_PRODUCTOS_SYNC.EMPNIT = COMMUNITY_INVSALDO_SYNC.EMPNIT
  WHERE (COMMUNITY_INVSALDO_SYNC.TOKEN = '${token}')`;

	execute.Query(res,qr);

});
// OBTIENE EL INVENTARIO DE UN SOLO PRODUCTO
router.get("/inventarioproducto", async(req,res)=>{
  
  const token = req.query.token;
  const filtro = req.query.filtro;
  
  let qr = `SELECT COMMUNITY_INVSALDO_SYNC.EMPNIT, COMMUNITY_EMPRESAS_SYNC.EMPNOMBRE, COMMUNITY_INVSALDO_SYNC.CODPROD, COMMUNITY_PRODUCTOS_SYNC.DESPROD, COMMUNITY_INVSALDO_SYNC.ENTRADAS, 
  COMMUNITY_INVSALDO_SYNC.SALIDAS, COMMUNITY_INVSALDO_SYNC.SALDO, COMMUNITY_MARCAS.DESMARCA, COMMUNITY_PRODUCTOS_SYNC.COSTO, (ISNULL((COMMUNITY_PRODUCTOS_SYNC.COSTO * COMMUNITY_INVSALDO_SYNC.SALDO),0)) AS TOTALCOSTO
  FROM COMMUNITY_MARCAS RIGHT OUTER JOIN
  COMMUNITY_PRODUCTOS_SYNC ON COMMUNITY_MARCAS.TOKEN = COMMUNITY_PRODUCTOS_SYNC.TOKEN AND COMMUNITY_MARCAS.CODMARCA = COMMUNITY_PRODUCTOS_SYNC.CODMARCA AND 
  COMMUNITY_MARCAS.EMPNIT = COMMUNITY_PRODUCTOS_SYNC.EMPNIT RIGHT OUTER JOIN
  COMMUNITY_INVSALDO_SYNC LEFT OUTER JOIN
  COMMUNITY_EMPRESAS_SYNC ON COMMUNITY_INVSALDO_SYNC.TOKEN = COMMUNITY_EMPRESAS_SYNC.TOKEN AND 
  COMMUNITY_INVSALDO_SYNC.EMPNIT = COMMUNITY_EMPRESAS_SYNC.EMPNIT ON COMMUNITY_PRODUCTOS_SYNC.TOKEN = COMMUNITY_INVSALDO_SYNC.TOKEN AND 
  COMMUNITY_PRODUCTOS_SYNC.CODPROD = COMMUNITY_INVSALDO_SYNC.CODPROD AND COMMUNITY_PRODUCTOS_SYNC.EMPNIT = COMMUNITY_INVSALDO_SYNC.EMPNIT
  WHERE (COMMUNITY_INVSALDO_SYNC.TOKEN = '${token}') AND (COMMUNITY_PRODUCTOS_SYNC.DESPROD LIKE '%${filtro}%') AND (COMMUNITY_PRODUCTOS_SYNC.HABILITADO='SI')`;

	execute.Query(res,qr);

});

// OBTIENE EL DETALLE DE LOS PRODUCTOS
router.get("/preciosproducto", async(req,res)=>{
  
  const {token,codprod,empnit} = req.query;
  
  let qr = `SELECT CODMEDIDA,EQUIVALE,COSTO,PRECIO,MAYOREOA,MAYOREOB,MAYOREOC FROM COMMUNITY_PRECIOS_SYNC WHERE TOKEN='${token}' AND EMPNIT='${empnit}' AND CODPROD='${codprod}'`

	execute.Query(res,qr);

});

// OBTIENE LA LISTA DE EMPRESAS
router.get("/empresas", async(req,res)=>{
  
  const token = req.query.token;
  
  let qr = `SELECT EMPNIT, EMPNOMBRE AS EMPRESA FROM COMMUNITY_EMPRESAS_SYNC WHERE TOKEN='${token}'`

	execute.Query(res,qr);

});

//////////////////////////////
// VENTAS
//////////////////////////////

// VENTAS POR DIA
router.get("/ventasmesdia", async(req,res)=>{
  
  const {token,anio,mes} = req.query;
  
  let qr = `SELECT COMMUNITY_DOCUMENTOS_SYNC.EMPNIT, COMMUNITY_EMPRESAS_SYNC.EMPNOMBRE, 
  COMMUNITY_DOCUMENTOS_SYNC.DIA, 
  SUM(COMMUNITY_DOCUMENTOS_SYNC.TOTALCOSTO) AS TOTALCOSTO,
        SUM(COMMUNITY_DOCUMENTOS_SYNC.TOTALPRECIO) AS TOTALPRECIO, 
  SUM(COMMUNITY_DOCUMENTOS_SYNC.RECARGOTARJETA) AS RECARGOTARJETA,
  (SUM(COMMUNITY_DOCUMENTOS_SYNC.TOTALPRECIO) + SUM(COMMUNITY_DOCUMENTOS_SYNC.RECARGOTARJETA)) AS TOTALVENTAS,
  ((SUM(COMMUNITY_DOCUMENTOS_SYNC.TOTALPRECIO) + SUM(COMMUNITY_DOCUMENTOS_SYNC.RECARGOTARJETA))-SUM(COMMUNITY_DOCUMENTOS_SYNC.TOTALCOSTO)) AS UTILIDAD
  FROM COMMUNITY_DOCUMENTOS_SYNC LEFT OUTER JOIN
                     COMMUNITY_EMPRESAS_SYNC ON COMMUNITY_DOCUMENTOS_SYNC.TOKEN = COMMUNITY_EMPRESAS_SYNC.TOKEN AND 
                     COMMUNITY_DOCUMENTOS_SYNC.EMPNIT = COMMUNITY_EMPRESAS_SYNC.EMPNIT
  WHERE (COMMUNITY_DOCUMENTOS_SYNC.ANIO = ${anio}) AND (COMMUNITY_DOCUMENTOS_SYNC.MES = ${mes}) AND (COMMUNITY_DOCUMENTOS_SYNC.STATUS <> 'A') AND 
                     (COMMUNITY_DOCUMENTOS_SYNC.TOKEN = '${token}')
  GROUP BY COMMUNITY_DOCUMENTOS_SYNC.EMPNIT, COMMUNITY_EMPRESAS_SYNC.EMPNOMBRE, COMMUNITY_DOCUMENTOS_SYNC.DIA`

	execute.Query(res,qr);

});
// VENTAS DEL DIA
router.get("/ventasdia", async(req,res)=>{
  
  const {token,empnit,dia} = req.query;
  
  let qr = `SELECT EMPNIT, DIA, CODDOC, CORRELATIVO, DOC_NOMCLIE AS CLIENTE, TOTALCOSTO AS COSTO, TOTALPRECIO AS PRECIO, RECARGOTARJETA AS RECARGO, (TOTALPRECIO+RECARGOTARJETA) AS IMPORTE,(TOTALPRECIO+RECARGOTARJETA)-TOTALCOSTO AS UTILIDAD
          FROM COMMUNITY_DOCUMENTOS_SYNC
          WHERE (EMPNIT = '${empnit}') AND (DIA = ${dia}) AND (STATUS <> 'A') AND (TOKEN = '${token}')
          ORDER BY DIA`

	execute.Query(res,qr);

});

router.get("/cortesmes",async(req,res)=>{

const {empnit,anio,mes,token} = req.query;

  let qry = `SELECT EMPNIT, FECHA, CONCAT(HORA,':',MINUTO) AS HORA, CORRELATIVO, TOTALVENTA AS VENTAS, TOTALRECIBOS AS RECIBOS, (TOTALVENTA+TOTALRECIBOS) AS INGRESOS, TOTALREPORTADO AS REPORTADO, FALTANTE, SOBRANTE, OBS ,
            USUARIO
            FROM  COMMUNITY_CORTES_SYNC
            WHERE (EMPNIT = '${empnit}') AND (ANIO = ${anio}) AND (MES = ${mes}) AND (TOKEN = '${token}')
            ORDER BY FECHA`;
  
  execute.Query(res,qry);

})
// DOCUMENTOS DEL CORTE
router.get("/ventascorte", async(req,res)=>{
  
  const {token,empnit,correlativo} = req.query;
  
  let qr = `SELECT EMPNIT, CONCAT(HORA,':',MINUTO) AS HORA,FECHA, CODDOC, CORRELATIVO, DOC_NOMCLIE AS CLIENTE, TOTALCOSTO AS COSTO, TOTALPRECIO AS PRECIO, RECARGOTARJETA AS RECARGO, (TOTALPRECIO+RECARGOTARJETA) AS IMPORTE,(TOTALPRECIO+RECARGOTARJETA)-TOTALCOSTO AS UTILIDAD
          FROM COMMUNITY_DOCUMENTOS_SYNC
          WHERE (EMPNIT = '${empnit}') AND (NOCORTE = ${correlativo}) AND (STATUS <> 'A') AND (TOKEN = '${token}')
          ORDER BY DIA`

          console.log()
	execute.Query(res,qr);

});


module.exports = router;
